# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "feedisco"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Romain Champourlier"]
  s.date = "2012-10-18"
  s.description = "Feedisco is a small and lightweight library focused on RSS/Atom feed discovery. It is intended to do little, but to do it well!"
  s.email = "romain@softr.li"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "feedisco.gemspec",
    "lib/feedisco.rb",
    "lib/feedisco/checks.rb",
    "lib/feedisco/discovery.rb",
    "lib/feedisco/utilities.rb",
    "lib/feedisco/version.rb",
    "script/console",
    "spec/fixtures/alternate.html",
    "spec/fixtures/no_link.html",
    "spec/fixtures/one_link_in_body.html",
    "spec/fixtures/several_links.html",
    "spec/lib/checks_spec.rb",
    "spec/lib/discovery_spec.rb",
    "spec/lib/utilities_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/rchampourlier/feedisco"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A simple feed discovery library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

